name: 'SWM GitHub Actions Basic'

# push가 일어나면 실행됨
on: push

# 질문 하나의 잡을 사용하는 것과 두 개의 잡을 사용하는 것에 차이가 있을 까?


# phase0 : 레벨이 나눠짐 - workflow - jobs - task(steps)git
#   Job마다 가상머신(빌드 서버)가 하나씩 붙음(window, mac, ubuntu)
# phase1 : 각 명령어 설명
# phase2 : Level마다 env(환경 변수) 넣고 접근범위 확인
#   - shell 마다 환경변수를 표현하는 방식이 다름(bash, pwsh 등...)
#   - 런타임에서 환경변수 변경하기(with GITHUB_ENV)
#   - steps에서 나오는 아웃풋 변수를 이용하기
#     - 언제 환경변수를 사용하고 어쩔때 언제 값을 사용할까?
#   - GitHubAction에서 민감한 정보 숨기기
#   - 배포 키와 같은 것은 소스코드에 넣어 놓으면 안됨! 어떻게 숨길까? - GitHub에서 Secret값 추가
# phase3 : 협업 시 프레임워크/라이브러리 버전 때문에 충돌이 일어나는 것 어떻게 해결할 수 있을까?
#   - 


jobs:
  first-job:
    name: 'First Job'

    strategy:
      matrix:
        os: [ 'ubuntu-latest', 'macos-latest', 'window-latest' ]
        message: ['HELLO WORLD', 'LOREM IPSUM' ]
    # 3가지 OS에서 다 돌아감
    runs-on: ${{ matrix.os }}

    steps:
    - name: 'Set output Value'
      id: first
      shell: bash
      run: |
        var_1="This is the value: ${{ matrix.message }}"
        
        echo "::set-output name=first_value::$var_1"

    - name: 'Check output value on ${{ matrix.os }}'
      shell: pwsh
      run: |
        echo "${{ steps.first.outputs.first_value }}"
